virtfs-proxy-helper.c: fix compile error
This is caused by a linux/xattr.h and sys/xattr.h incompatibility:

    In file included from /home/snoonan/Development/qemu/include/qemu/xattr.h:27:0,
		     from fsdev/virtfs-proxy-helper.c:25:
    /usr/include/sys/xattr.h:31:3: error: expected identifier before numeric constant
       XATTR_CREATE = 1, /* set value, fail if attr already exists.  */
       ^
    /home/snoonan/Development/qemu/qemu/rules.mak:25: recipe for target 'fsdev/virtfs-proxy-helper.o' failed

Moving the include around resolves it.

Change-Id: I8242070c18a511e62877d57564a7ad754a8f14c8
Signed-off-by: Steven Noonan <snoonan@amazon.com>
Cc: Anthony Liguori <aliguori@amazon.com>